version: 38
jobs:
  - name: Mirror
    steps:
      - !PullRepository
        name: Mirror
        remoteUrl: https://github.com/narumii/Deobfuscator
        targetProject: Deobfuscator
        accessTokenSecret: CunnyDev Token
        refs: refs/heads/* refs/tags/*
        withLfs: false
        force: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !ScheduleTrigger
        cronExpression: 0 0 1 * * ?
        projects: Deobfuscator
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 14400
